SELECT CUSTOMERS.id, CUSTOMERS.NAME, MANAGERS.NAME, ORDERS.AMOUNT, ORDERS.DATE
FROM CUSTOMERS 
JOIN MANAGERS on CUSTOMERS.MANAGERID = MANAGERS.ID
JOIN ORDERS ON CUSTOMERS.ID == ORDERS.CUSTOMERID AND ORDERS.AMOUNT >= 1000 AND ORDERS.DATE > '2023-01-01';